### ISSUE TITLE
erro no carregamento das tabelas do usuario

### ISSUE THREAD

**Issue by profsergiocosta** [mapbiomas-brazil/user-toolkit#12]
Prezados

Observei que ele nao pega as tabelas que estao na pasta Mapbiomas. Fiz uma modificacao no codigo para ele filtrar as "pastas" com MAPBIOMAS:

sem mexer muito no codigo:

       `var roots = ee.data.getAssetRoots()
                .map(
                    function (obj) {
                        return obj.id;
                    });

            roots = roots.filter(function(caminho) {
              return caminho.indexOf('/MAPBIOMAS') !=-1;
            });
            
            var allTablesNames;

            /**
             * Skip the error msg if MAPBIOMAS folder is not found
             */
  
            try {
                var tablesNames = ee.data.getList({
                    'id': roots[0] 
                }).map(
                    function (obj) {
                        return obj.id;
                    });

                allTablesNames = App.options.tables[regionName].concat(tablesNames);
            }
            catch (e) {
                allTablesNames = App.options.tables[regionName];
            }`

o script completo

https://code.earthengine.google.com/7250f45585fec41a81b1bb4e1045b246?accept_repo=users%2Fmapbiomas%2Fuser-toolkit

**Comment by joaosiqueira** [comment]
Oi Sergio, muito obrigado por identificar e corrigir o problema. Já atualizei no repositório do @mapbiomas:

[mapbiomas-user-toolkit-lulc.js](https://github.com/mapbiomas/brazil-user-toolkit/blob/main/mapbiomas-user-toolkit-lulc.js)

Att,

João Siqueira
